<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class BookingSlotsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('booking_slots')->delete();
        
        \DB::table('booking_slots')->insert(array (
            0 => 
            array (
                'id' => 1,
                'doctor_id' => 2,
                'patient_id' => 10,
                'booking_date' => '2024-08-01',
                'slot_start_time' => '09:40:00',
                'slot_end_time' => '10:10:00',
                'note' => 'Est sapiente nihil',
                'image' => '',
                'invoice_url' => NULL,
                'insurance' => '1',
                'symptoms' => 'Quod nobis velit vo',
                'status' => 'cancelled',
                'created_at' => '2024-08-01 11:29:53',
                'updated_at' => '2024-08-02 05:38:45',
            ),
            1 => 
            array (
                'id' => 2,
                'doctor_id' => 1,
                'patient_id' => 6,
                'booking_date' => '2024-08-01',
                'slot_start_time' => '09:40:00',
                'slot_end_time' => '10:10:00',
                'note' => 'Est sapiente nihil',
                'image' => '',
                'invoice_url' => NULL,
                'insurance' => '1',
                'symptoms' => 'Quod nobis velit vo',
                'status' => 'requested',
                'created_at' => '2024-08-01 11:29:53',
                'updated_at' => '2024-08-01 11:29:53',
            ),
            2 => 
            array (
                'id' => 3,
                'doctor_id' => 2,
                'patient_id' => 6,
                'booking_date' => '2024-08-01',
                'slot_start_time' => '11:40:00',
                'slot_end_time' => '12:10:00',
                'note' => 'Voluptate quia quis',
                'image' => '',
                'invoice_url' => NULL,
                'insurance' => '1',
                'symptoms' => 'Duis numquam aut sun',
                'status' => 'requested',
                'created_at' => '2024-08-01 11:30:33',
                'updated_at' => '2024-08-02 05:40:42',
            ),
            3 => 
            array (
                'id' => 4,
                'doctor_id' => 2,
                'patient_id' => 9,
                'booking_date' => '2024-08-05',
                'slot_start_time' => '10:20:00',
                'slot_end_time' => '10:50:00',
                'note' => 'Distinctio Nulla om',
                'image' => '',
                'invoice_url' => NULL,
                'insurance' => '1',
                'symptoms' => 'Aut numquam qui iste',
                'status' => 'requested',
                'created_at' => '2024-08-01 11:30:49',
                'updated_at' => '2024-08-02 07:15:23',
            ),
            4 => 
            array (
                'id' => 5,
                'doctor_id' => 2,
                'patient_id' => 6,
                'booking_date' => '2024-08-13',
                'slot_start_time' => '11:40:00',
                'slot_end_time' => '12:10:00',
                'note' => 'Amet placeat dicta',
                'image' => '',
                'invoice_url' => NULL,
                'insurance' => '0',
                'symptoms' => 'Voluptas voluptatem',
                'status' => 'confirmed',
                'created_at' => '2024-08-01 11:31:01',
                'updated_at' => '2024-08-01 12:14:04',
            ),
            5 => 
            array (
                'id' => 6,
                'doctor_id' => 2,
                'patient_id' => 6,
                'booking_date' => '2024-08-21',
                'slot_start_time' => '12:20:00',
                'slot_end_time' => '12:50:00',
                'note' => 'Corrupti fuga Veni',
                'image' => '',
                'invoice_url' => NULL,
                'insurance' => '0',
                'symptoms' => 'Rerum maxime qui ali',
                'status' => 'confirmed',
                'created_at' => '2024-08-01 11:31:14',
                'updated_at' => '2024-08-01 12:13:37',
            ),
            6 => 
            array (
                'id' => 7,
                'doctor_id' => 1,
                'patient_id' => 6,
                'booking_date' => '2024-08-02',
                'slot_start_time' => '10:20:00',
                'slot_end_time' => '10:50:00',
                'note' => 'Doloremque incidunt',
                'image' => '',
                'invoice_url' => NULL,
                'insurance' => '0',
                'symptoms' => 'Et ipsum aperiam sit',
                'status' => 'requested',
                'created_at' => '2024-08-01 11:31:34',
                'updated_at' => '2024-08-01 11:31:34',
            ),
            7 => 
            array (
                'id' => 8,
                'doctor_id' => 1,
                'patient_id' => 6,
                'booking_date' => '2024-08-05',
                'slot_start_time' => '10:20:00',
                'slot_end_time' => '10:50:00',
                'note' => 'Distinctio Molestia',
                'image' => '',
                'invoice_url' => NULL,
                'insurance' => '0',
                'symptoms' => 'Ea aut at consequatu',
                'status' => 'requested',
                'created_at' => '2024-08-01 11:31:51',
                'updated_at' => '2024-08-01 11:31:51',
            ),
            8 => 
            array (
                'id' => 9,
                'doctor_id' => 1,
                'patient_id' => 6,
                'booking_date' => '2024-08-07',
                'slot_start_time' => '09:00:00',
                'slot_end_time' => '09:30:00',
                'note' => 'Testing',
                'image' => '',
                'invoice_url' => NULL,
                'insurance' => '0',
                'symptoms' => 'Testing',
                'status' => 'requested',
                'created_at' => '2024-08-01 11:39:35',
                'updated_at' => '2024-08-01 11:39:35',
            ),
            9 => 
            array (
                'id' => 10,
                'doctor_id' => 1,
                'patient_id' => 6,
                'booking_date' => '2024-08-02',
                'slot_start_time' => '12:20:00',
                'slot_end_time' => '12:50:00',
                'note' => 'Fugiat provident la',
                'image' => '',
                'invoice_url' => NULL,
                'insurance' => '0',
                'symptoms' => 'Itaque ratione labor',
                'status' => 'requested',
                'created_at' => '2024-08-01 11:40:32',
                'updated_at' => '2024-08-01 11:40:32',
            ),
            10 => 
            array (
                'id' => 11,
                'doctor_id' => 1,
                'patient_id' => 6,
                'booking_date' => '2024-08-07',
                'slot_start_time' => '10:20:00',
                'slot_end_time' => '10:50:00',
                'note' => 'Temporibus id in opt',
                'image' => '',
                'invoice_url' => NULL,
                'insurance' => '0',
                'symptoms' => 'Dolor qui dolores qu',
                'status' => 'requested',
                'created_at' => '2024-08-01 11:40:49',
                'updated_at' => '2024-08-01 11:40:49',
            ),
            11 => 
            array (
                'id' => 12,
                'doctor_id' => 1,
                'patient_id' => 6,
                'booking_date' => '2024-08-21',
                'slot_start_time' => '10:20:00',
                'slot_end_time' => '10:50:00',
                'note' => 'Et perferendis qui p',
                'image' => '',
                'invoice_url' => NULL,
                'insurance' => '1',
                'symptoms' => 'Aut id velit dolor e',
                'status' => 'requested',
                'created_at' => '2024-08-01 11:41:04',
                'updated_at' => '2024-08-01 11:41:04',
            ),
            12 => 
            array (
                'id' => 13,
                'doctor_id' => 3,
                'patient_id' => 6,
                'booking_date' => '2024-08-10',
                'slot_start_time' => '09:40:00',
                'slot_end_time' => '10:10:00',
                'note' => 'qwerty',
                'image' => '',
                'invoice_url' => NULL,
                'insurance' => '0',
                'symptoms' => NULL,
                'status' => 'confirmed',
                'created_at' => '2024-08-01 11:42:41',
                'updated_at' => '2024-08-02 07:52:08',
            ),
            13 => 
            array (
                'id' => 14,
                'doctor_id' => 3,
                'patient_id' => 7,
                'booking_date' => '2024-08-01',
                'slot_start_time' => '10:20:00',
                'slot_end_time' => '10:50:00',
                'note' => 'Odio do laudantium',
                'image' => '',
                'invoice_url' => NULL,
                'insurance' => '1',
                'symptoms' => 'Voluptatem inventore',
                'status' => 'requested',
                'created_at' => '2024-08-01 11:45:44',
                'updated_at' => '2024-08-01 11:45:44',
            ),
            14 => 
            array (
                'id' => 15,
                'doctor_id' => 3,
                'patient_id' => 7,
                'booking_date' => '2024-08-05',
                'slot_start_time' => '10:20:00',
                'slot_end_time' => '10:50:00',
                'note' => 'Aspernatur eum amet',
                'image' => '',
                'invoice_url' => NULL,
                'insurance' => '1',
                'symptoms' => 'Doloribus nostrum nu',
                'status' => 'requested',
                'created_at' => '2024-08-01 11:46:02',
                'updated_at' => '2024-08-01 11:46:02',
            ),
            15 => 
            array (
                'id' => 16,
                'doctor_id' => 1,
                'patient_id' => 7,
                'booking_date' => '2024-08-03',
                'slot_start_time' => '11:00:00',
                'slot_end_time' => '11:30:00',
                'note' => 'Cumque natus molliti',
                'image' => '',
                'invoice_url' => NULL,
                'insurance' => '1',
                'symptoms' => 'Fugiat omnis vitae',
                'status' => 'requested',
                'created_at' => '2024-08-01 11:55:05',
                'updated_at' => '2024-08-01 11:55:05',
            ),
            16 => 
            array (
                'id' => 17,
                'doctor_id' => 5,
                'patient_id' => 7,
                'booking_date' => '2024-08-01',
                'slot_start_time' => '11:00:00',
                'slot_end_time' => '11:30:00',
                'note' => 'Rem id duis eius ne',
                'image' => '',
                'invoice_url' => NULL,
                'insurance' => '1',
                'symptoms' => 'Porro est dolore vol',
                'status' => 'requested',
                'created_at' => '2024-08-01 11:55:23',
                'updated_at' => '2024-08-01 11:55:23',
            ),
            17 => 
            array (
                'id' => 18,
                'doctor_id' => 1,
                'patient_id' => 7,
                'booking_date' => '2024-08-07',
                'slot_start_time' => '12:20:00',
                'slot_end_time' => '12:50:00',
                'note' => 'Velit ut molestias',
                'image' => '',
                'invoice_url' => NULL,
                'insurance' => '1',
                'symptoms' => 'Est maxime ea moles',
                'status' => 'requested',
                'created_at' => '2024-08-01 11:55:46',
                'updated_at' => '2024-08-01 11:55:46',
            ),
            18 => 
            array (
                'id' => 19,
                'doctor_id' => 4,
                'patient_id' => 7,
                'booking_date' => '2024-08-01',
                'slot_start_time' => '09:40:00',
                'slot_end_time' => '10:10:00',
                'note' => 'Enim assumenda at op',
                'image' => '',
                'invoice_url' => NULL,
                'insurance' => '0',
                'symptoms' => 'Et cum aliquip quam',
                'status' => 'requested',
                'created_at' => '2024-08-01 11:56:10',
                'updated_at' => '2024-08-01 11:56:10',
            ),
            19 => 
            array (
                'id' => 20,
                'doctor_id' => 1,
                'patient_id' => 7,
                'booking_date' => '2024-08-01',
                'slot_start_time' => '11:00:00',
                'slot_end_time' => '11:30:00',
                'note' => 'Dignissimos sunt fug',
                'image' => '',
                'invoice_url' => NULL,
                'insurance' => '0',
                'symptoms' => 'Aut iure aut excepte',
                'status' => 'requested',
                'created_at' => '2024-08-01 11:56:26',
                'updated_at' => '2024-08-01 11:56:26',
            ),
            20 => 
            array (
                'id' => 21,
                'doctor_id' => 4,
                'patient_id' => 7,
                'booking_date' => '2024-08-02',
                'slot_start_time' => '09:40:00',
                'slot_end_time' => '10:10:00',
                'note' => 'Ex assumenda culpa',
                'image' => '',
                'invoice_url' => NULL,
                'insurance' => '1',
                'symptoms' => 'Consequat Ducimus',
                'status' => 'requested',
                'created_at' => '2024-08-01 11:56:44',
                'updated_at' => '2024-08-01 11:56:44',
            ),
            21 => 
            array (
                'id' => 22,
                'doctor_id' => 3,
                'patient_id' => 9,
                'booking_date' => '2024-08-01',
                'slot_start_time' => '11:00:00',
                'slot_end_time' => '11:30:00',
                'note' => 'Et repudiandae enim',
                'image' => '',
                'invoice_url' => NULL,
                'insurance' => '0',
                'symptoms' => 'Incidunt iusto et d',
                'status' => 'requested',
                'created_at' => '2024-08-01 12:47:42',
                'updated_at' => '2024-08-01 12:47:42',
            ),
            22 => 
            array (
                'id' => 23,
                'doctor_id' => 3,
                'patient_id' => 6,
                'booking_date' => '2024-08-16',
                'slot_start_time' => '09:40:00',
                'slot_end_time' => '10:10:00',
                'note' => 'qwerty',
                'image' => '',
                'invoice_url' => NULL,
                'insurance' => '0',
                'symptoms' => NULL,
                'status' => 'requested',
                'created_at' => '2024-08-02 04:51:13',
                'updated_at' => '2024-08-02 04:51:13',
            ),
            23 => 
            array (
                'id' => 24,
                'doctor_id' => 2,
                'patient_id' => 6,
                'booking_date' => '2024-08-08',
                'slot_start_time' => '10:20:00',
                'slot_end_time' => '10:50:00',
                'note' => 'Facere ipsum et quis',
                'image' => '',
                'invoice_url' => NULL,
                'insurance' => '0',
                'symptoms' => 'Sed amet earum eu q',
                'status' => 'confirmed',
                'created_at' => '2024-08-02 05:06:19',
                'updated_at' => '2024-08-02 07:14:36',
            ),
            24 => 
            array (
                'id' => 25,
                'doctor_id' => 2,
                'patient_id' => 6,
                'booking_date' => '2024-08-03',
                'slot_start_time' => '11:00:00',
                'slot_end_time' => '11:30:00',
                'note' => 'testing',
                'image' => '',
                'invoice_url' => NULL,
                'insurance' => '1',
                'symptoms' => NULL,
                'status' => 'requested',
                'created_at' => '2024-08-02 05:07:55',
                'updated_at' => '2024-08-02 07:14:07',
            ),
            25 => 
            array (
                'id' => 26,
                'doctor_id' => 2,
                'patient_id' => 10,
                'booking_date' => '2024-08-16',
                'slot_start_time' => '11:40:00',
                'slot_end_time' => '12:10:00',
                'note' => 'Qui id aut ad fugit',
                'image' => '',
                'invoice_url' => NULL,
                'insurance' => '1',
                'symptoms' => 'Repudiandae veniam',
                'status' => 'requested',
                'created_at' => '2024-08-02 05:08:42',
                'updated_at' => '2024-08-02 07:44:54',
            ),
            26 => 
            array (
                'id' => 27,
                'doctor_id' => 2,
                'patient_id' => 6,
                'booking_date' => '2024-08-02',
                'slot_start_time' => '10:20:00',
                'slot_end_time' => '10:50:00',
                'note' => 'testing',
                'image' => '',
                'invoice_url' => NULL,
                'insurance' => '1',
                'symptoms' => NULL,
                'status' => 'confirmed',
                'created_at' => '2024-08-02 05:40:06',
                'updated_at' => '2024-08-02 07:26:46',
            ),
            27 => 
            array (
                'id' => 28,
                'doctor_id' => 4,
                'patient_id' => 7,
                'booking_date' => '2024-08-09',
                'slot_start_time' => '10:20:00',
                'slot_end_time' => '10:50:00',
                'note' => 'Atque fugiat in nec',
                'image' => '',
                'invoice_url' => NULL,
                'insurance' => '1',
                'symptoms' => 'Labore est quis sin',
                'status' => 'requested',
                'created_at' => '2024-08-02 06:20:57',
                'updated_at' => '2024-08-02 06:20:57',
            ),
            28 => 
            array (
                'id' => 29,
                'doctor_id' => 3,
                'patient_id' => 14,
                'booking_date' => '2024-08-05',
                'slot_start_time' => '12:20:00',
                'slot_end_time' => '12:50:00',
                'note' => 'Molestiae harum iste',
                'image' => '',
                'invoice_url' => NULL,
                'insurance' => '1',
                'symptoms' => 'Asperiores ducimus',
                'status' => 'requested',
                'created_at' => '2024-08-02 07:47:19',
                'updated_at' => '2024-08-02 07:47:19',
            ),
            29 => 
            array (
                'id' => 30,
                'doctor_id' => 3,
                'patient_id' => 16,
                'booking_date' => '2024-08-21',
                'slot_start_time' => '11:40:00',
                'slot_end_time' => '12:10:00',
                'note' => 'Placeat non labore',
                'image' => '',
                'invoice_url' => NULL,
                'insurance' => '1',
                'symptoms' => 'Anim eos dolor elit',
                'status' => 'requested',
                'created_at' => '2024-08-02 07:47:36',
                'updated_at' => '2024-08-02 07:47:36',
            ),
            30 => 
            array (
                'id' => 31,
                'doctor_id' => 3,
                'patient_id' => 7,
                'booking_date' => '2024-08-10',
                'slot_start_time' => '11:40:00',
                'slot_end_time' => '12:10:00',
                'note' => 'Accusamus ea id cons',
                'image' => '',
                'invoice_url' => NULL,
                'insurance' => '0',
                'symptoms' => 'Autem molestias reru',
                'status' => 'confirmed',
                'created_at' => '2024-08-02 07:47:53',
                'updated_at' => '2024-08-02 07:52:19',
            ),
            31 => 
            array (
                'id' => 32,
                'doctor_id' => 2,
                'patient_id' => 6,
                'booking_date' => '2024-08-20',
                'slot_start_time' => '10:20:00',
                'slot_end_time' => '10:50:00',
                'note' => 'Laborum cum atque re',
                'image' => '',
                'invoice_url' => NULL,
                'insurance' => '1',
                'symptoms' => 'Vel eaque sunt sint',
                'status' => 'requested',
                'created_at' => '2024-08-02 07:48:15',
                'updated_at' => '2024-08-02 07:48:15',
            ),
            32 => 
            array (
                'id' => 33,
                'doctor_id' => 2,
                'patient_id' => 8,
                'booking_date' => '2024-08-15',
                'slot_start_time' => '11:40:00',
                'slot_end_time' => '12:10:00',
                'note' => 'Eveniet incididunt',
                'image' => '',
                'invoice_url' => NULL,
                'insurance' => '1',
                'symptoms' => 'Quis doloribus in do',
                'status' => 'requested',
                'created_at' => '2024-08-02 07:48:25',
                'updated_at' => '2024-08-02 07:48:25',
            ),
            33 => 
            array (
                'id' => 34,
                'doctor_id' => 2,
                'patient_id' => 8,
                'booking_date' => '2024-08-20',
                'slot_start_time' => '11:40:00',
                'slot_end_time' => '12:10:00',
                'note' => 'Molestiae enim ut vo',
                'image' => '',
                'invoice_url' => NULL,
                'insurance' => '0',
                'symptoms' => 'Irure qui commodi po',
                'status' => 'requested',
                'created_at' => '2024-08-02 07:48:44',
                'updated_at' => '2024-08-02 07:48:44',
            ),
            34 => 
            array (
                'id' => 35,
                'doctor_id' => 2,
                'patient_id' => 8,
                'booking_date' => '2024-08-07',
                'slot_start_time' => '11:00:00',
                'slot_end_time' => '11:30:00',
                'note' => 'Ut deleniti rem sunt',
                'image' => '',
                'invoice_url' => NULL,
                'insurance' => '1',
                'symptoms' => 'Aut vitae eum mollit',
                'status' => 'requested',
                'created_at' => '2024-08-02 07:48:57',
                'updated_at' => '2024-08-02 07:48:57',
            ),
            35 => 
            array (
                'id' => 36,
                'doctor_id' => 2,
                'patient_id' => 16,
                'booking_date' => '2024-08-06',
                'slot_start_time' => '09:40:00',
                'slot_end_time' => '10:10:00',
                'note' => 'Eligendi blanditiis',
                'image' => '',
                'invoice_url' => NULL,
                'insurance' => '0',
                'symptoms' => 'Itaque commodo quaer',
                'status' => 'requested',
                'created_at' => '2024-08-02 07:49:14',
                'updated_at' => '2024-08-02 07:58:31',
            ),
            36 => 
            array (
                'id' => 37,
                'doctor_id' => 2,
                'patient_id' => 16,
                'booking_date' => '2024-08-06',
                'slot_start_time' => '11:00:00',
                'slot_end_time' => '11:30:00',
                'note' => 'Ratione molestiae te',
                'image' => '',
                'invoice_url' => NULL,
                'insurance' => '0',
                'symptoms' => 'Minima tenetur irure',
                'status' => 'requested',
                'created_at' => '2024-08-02 07:49:42',
                'updated_at' => '2024-08-02 07:58:55',
            ),
            37 => 
            array (
                'id' => 38,
                'doctor_id' => 2,
                'patient_id' => 10,
                'booking_date' => '2024-08-19',
                'slot_start_time' => '11:00:00',
                'slot_end_time' => '11:30:00',
                'note' => 'Doloremque rem ullam',
                'image' => '',
                'invoice_url' => NULL,
                'insurance' => '1',
                'symptoms' => 'Recusandae Ullam ve',
                'status' => 'requested',
                'created_at' => '2024-08-02 07:49:54',
                'updated_at' => '2024-08-02 07:49:54',
            ),
            38 => 
            array (
                'id' => 39,
                'doctor_id' => 2,
                'patient_id' => 8,
                'booking_date' => '2024-08-19',
                'slot_start_time' => '13:00:00',
                'slot_end_time' => '13:30:00',
                'note' => 'Sit iure et officia',
                'image' => '',
                'invoice_url' => NULL,
                'insurance' => '1',
                'symptoms' => 'Qui praesentium veli',
                'status' => 'requested',
                'created_at' => '2024-08-02 07:50:06',
                'updated_at' => '2024-08-02 07:50:06',
            ),
            39 => 
            array (
                'id' => 40,
                'doctor_id' => 3,
                'patient_id' => 16,
                'booking_date' => '2024-08-08',
                'slot_start_time' => '11:40:00',
                'slot_end_time' => '12:10:00',
                'note' => 'Omnis nesciunt irur',
                'image' => '',
                'invoice_url' => NULL,
                'insurance' => '0',
                'symptoms' => 'Sit est tempor aspe',
                'status' => 'requested',
                'created_at' => '2024-08-02 07:50:39',
                'updated_at' => '2024-08-02 07:50:39',
            ),
            40 => 
            array (
                'id' => 41,
                'doctor_id' => 3,
                'patient_id' => 16,
                'booking_date' => '2024-08-20',
                'slot_start_time' => '13:40:00',
                'slot_end_time' => '14:10:00',
                'note' => 'Animi aut amet vol',
                'image' => '',
                'invoice_url' => NULL,
                'insurance' => '0',
                'symptoms' => 'Deserunt qui eum dol',
                'status' => 'requested',
                'created_at' => '2024-08-02 07:50:54',
                'updated_at' => '2024-08-02 07:50:54',
            ),
            41 => 
            array (
                'id' => 42,
                'doctor_id' => 3,
                'patient_id' => 16,
                'booking_date' => '2024-08-21',
                'slot_start_time' => '10:20:00',
                'slot_end_time' => '10:50:00',
                'note' => 'Rerum aut qui mollit',
                'image' => '',
                'invoice_url' => NULL,
                'insurance' => '0',
                'symptoms' => 'Qui expedita suscipi',
                'status' => 'requested',
                'created_at' => '2024-08-02 07:51:41',
                'updated_at' => '2024-08-02 07:51:41',
            ),
            42 => 
            array (
                'id' => 43,
                'doctor_id' => 2,
                'patient_id' => 16,
                'booking_date' => '2024-08-14',
                'slot_start_time' => '10:20:00',
                'slot_end_time' => '10:50:00',
                'note' => 'Quibusdam sit eiusm',
                'image' => '',
                'invoice_url' => NULL,
                'insurance' => '0',
                'symptoms' => 'Id sunt omnis dolor',
                'status' => 'requested',
                'created_at' => '2024-08-02 08:44:59',
                'updated_at' => '2024-08-02 08:44:59',
            ),
            43 => 
            array (
                'id' => 44,
                'doctor_id' => 2,
                'patient_id' => 16,
                'booking_date' => '2024-08-15',
                'slot_start_time' => '12:20:00',
                'slot_end_time' => '12:50:00',
                'note' => 'Velit earum rerum et',
                'image' => '',
                'invoice_url' => NULL,
                'insurance' => '0',
                'symptoms' => 'Consequat Omnis nih',
                'status' => 'requested',
                'created_at' => '2024-08-02 08:45:10',
                'updated_at' => '2024-08-02 08:45:10',
            ),
            44 => 
            array (
                'id' => 45,
                'doctor_id' => 2,
                'patient_id' => 16,
                'booking_date' => '2024-08-19',
                'slot_start_time' => '11:40:00',
                'slot_end_time' => '12:10:00',
                'note' => 'Vero amet magnam qu',
                'image' => '',
                'invoice_url' => NULL,
                'insurance' => '1',
                'symptoms' => 'Praesentium dignissi',
                'status' => 'requested',
                'created_at' => '2024-08-02 08:45:20',
                'updated_at' => '2024-08-02 08:45:20',
            ),
            45 => 
            array (
                'id' => 46,
                'doctor_id' => 1,
                'patient_id' => 16,
                'booking_date' => '2024-08-15',
                'slot_start_time' => '13:00:00',
                'slot_end_time' => '13:30:00',
                'note' => 'Dolore quibusdam tot',
                'image' => '',
                'invoice_url' => NULL,
                'insurance' => '0',
                'symptoms' => 'Quia aliqua Explica',
                'status' => 'requested',
                'created_at' => '2024-08-02 08:46:01',
                'updated_at' => '2024-08-02 08:46:01',
            ),
            46 => 
            array (
                'id' => 47,
                'doctor_id' => 1,
                'patient_id' => 16,
                'booking_date' => '2024-08-14',
                'slot_start_time' => '11:40:00',
                'slot_end_time' => '12:10:00',
                'note' => 'Est accusantium et',
                'image' => '',
                'invoice_url' => NULL,
                'insurance' => '0',
                'symptoms' => 'Praesentium magnam n',
                'status' => 'requested',
                'created_at' => '2024-08-02 08:46:11',
                'updated_at' => '2024-08-02 08:46:11',
            ),
            47 => 
            array (
                'id' => 48,
                'doctor_id' => 1,
                'patient_id' => 16,
                'booking_date' => '2024-08-06',
                'slot_start_time' => '10:20:00',
                'slot_end_time' => '10:50:00',
                'note' => 'Delectus libero odi',
                'image' => '',
                'invoice_url' => NULL,
                'insurance' => '0',
                'symptoms' => 'Veniam pariatur Pa',
                'status' => 'requested',
                'created_at' => '2024-08-02 08:46:24',
                'updated_at' => '2024-08-02 08:46:24',
            ),
            48 => 
            array (
                'id' => 49,
                'doctor_id' => 2,
                'patient_id' => 14,
                'booking_date' => '2024-08-09',
                'slot_start_time' => '10:20:00',
                'slot_end_time' => '10:50:00',
                'note' => 'Error saepe autem la',
                'image' => '',
                'invoice_url' => NULL,
                'insurance' => '0',
                'symptoms' => 'Dolorum ipsam ut non',
                'status' => 'requested',
                'created_at' => '2024-08-02 08:53:45',
                'updated_at' => '2024-08-02 08:53:45',
            ),
            49 => 
            array (
                'id' => 50,
                'doctor_id' => 2,
                'patient_id' => 14,
                'booking_date' => '2024-08-14',
                'slot_start_time' => '11:00:00',
                'slot_end_time' => '11:30:00',
                'note' => 'Rerum sit ex deserun',
                'image' => '',
                'invoice_url' => NULL,
                'insurance' => '0',
                'symptoms' => 'Cumque libero labore',
                'status' => 'confirmed',
                'created_at' => '2024-08-02 08:53:58',
                'updated_at' => '2024-08-02 09:46:43',
            ),
            50 => 
            array (
                'id' => 51,
                'doctor_id' => 2,
                'patient_id' => 14,
                'booking_date' => '2024-08-20',
                'slot_start_time' => '11:00:00',
                'slot_end_time' => '11:30:00',
                'note' => 'Magnam ullamco natus',
                'image' => '',
                'invoice_url' => NULL,
                'insurance' => '1',
                'symptoms' => 'Nihil ducimus vero',
                'status' => 'confirmed',
                'created_at' => '2024-08-02 08:54:12',
                'updated_at' => '2024-08-02 09:43:36',
            ),
            51 => 
            array (
                'id' => 52,
                'doctor_id' => 1,
                'patient_id' => 14,
                'booking_date' => '2024-08-07',
                'slot_start_time' => '11:00:00',
                'slot_end_time' => '11:30:00',
                'note' => 'At nulla voluptatem',
                'image' => '',
                'invoice_url' => NULL,
                'insurance' => '1',
                'symptoms' => 'Irure amet ad conse',
                'status' => 'requested',
                'created_at' => '2024-08-02 08:54:32',
                'updated_at' => '2024-08-02 08:54:32',
            ),
            52 => 
            array (
                'id' => 53,
                'doctor_id' => 1,
                'patient_id' => 14,
                'booking_date' => '2024-08-14',
                'slot_start_time' => '10:20:00',
                'slot_end_time' => '10:50:00',
                'note' => 'Aperiam molestias pa',
                'image' => '',
                'invoice_url' => NULL,
                'insurance' => '1',
                'symptoms' => 'Consequat Earum nec',
                'status' => 'requested',
                'created_at' => '2024-08-02 08:54:43',
                'updated_at' => '2024-08-02 08:54:43',
            ),
            53 => 
            array (
                'id' => 54,
                'doctor_id' => 1,
                'patient_id' => 14,
                'booking_date' => '2024-08-21',
                'slot_start_time' => '11:40:00',
                'slot_end_time' => '12:10:00',
                'note' => 'Sint veritatis ut el',
                'image' => '',
                'invoice_url' => NULL,
                'insurance' => '1',
                'symptoms' => 'In minima similique',
                'status' => 'requested',
                'created_at' => '2024-08-02 08:54:57',
                'updated_at' => '2024-08-02 08:54:57',
            ),
            54 => 
            array (
                'id' => 55,
                'doctor_id' => 1,
                'patient_id' => 14,
                'booking_date' => '2024-08-19',
                'slot_start_time' => '12:20:00',
                'slot_end_time' => '12:50:00',
                'note' => 'Sed harum voluptatem',
                'image' => '',
                'invoice_url' => NULL,
                'insurance' => '1',
                'symptoms' => 'Saepe aut qui odit s',
                'status' => 'requested',
                'created_at' => '2024-08-02 08:55:11',
                'updated_at' => '2024-08-02 08:55:11',
            ),
            55 => 
            array (
                'id' => 56,
                'doctor_id' => 2,
                'patient_id' => 14,
                'booking_date' => '2024-08-02',
                'slot_start_time' => '11:00:00',
                'slot_end_time' => '11:30:00',
                'note' => 'Laudantium qui modi',
                'image' => '',
                'invoice_url' => NULL,
                'insurance' => '1',
                'symptoms' => 'Voluptas officia asp',
                'status' => 'confirmed',
                'created_at' => '2024-08-02 08:55:33',
                'updated_at' => '2024-08-02 08:59:15',
            ),
            56 => 
            array (
                'id' => 57,
                'doctor_id' => 4,
                'patient_id' => 14,
                'booking_date' => '2024-08-07',
                'slot_start_time' => '11:40:00',
                'slot_end_time' => '12:10:00',
                'note' => 'Eos assumenda eu ita',
                'image' => '',
                'invoice_url' => NULL,
                'insurance' => '0',
                'symptoms' => 'Est eos esse esse q',
                'status' => 'requested',
                'created_at' => '2024-08-02 08:55:53',
                'updated_at' => '2024-08-02 08:55:53',
            ),
            57 => 
            array (
                'id' => 58,
                'doctor_id' => 4,
                'patient_id' => 14,
                'booking_date' => '2024-08-21',
                'slot_start_time' => '11:00:00',
                'slot_end_time' => '11:30:00',
                'note' => 'Duis qui expedita mo',
                'image' => '',
                'invoice_url' => NULL,
                'insurance' => '1',
                'symptoms' => 'Possimus error expl',
                'status' => 'requested',
                'created_at' => '2024-08-02 08:56:05',
                'updated_at' => '2024-08-02 08:56:05',
            ),
            58 => 
            array (
                'id' => 59,
                'doctor_id' => 4,
                'patient_id' => 14,
                'booking_date' => '2024-08-21',
                'slot_start_time' => '09:40:00',
                'slot_end_time' => '10:10:00',
                'note' => 'Adipisci non totam n',
                'image' => '',
                'invoice_url' => NULL,
                'insurance' => '1',
                'symptoms' => 'Cupiditate quis obca',
                'status' => 'requested',
                'created_at' => '2024-08-02 08:56:26',
                'updated_at' => '2024-08-02 08:56:26',
            ),
        ));
        
        
    }
}